displayName: Mapcom Traefik Plugin
type: middleware
import: prod1gitlab.mapcom.local/development/traefikplugin
summary: 'Mapcom Traefik Plugin'
testData:
  Headers:
    X-Demo: test
    X-URL: '{{URL}}'
